SELECT NAME, CGPA FROM STUDENT
INNER JOIN STUDENT_RESULT ON STUDENT.ID= STUDENT_RESULT.ID AND STUDENT_RESULT.CGPA < 3.88


SELECT COUNT(*) FROM STUDENT
INNER JOIN STUDENT_RESULT ON STUDENT.ID= STUDENT_RESULT.ID
/*or*/
SELECT COUNT(*) FROM STUDENT_RESULT


SELECT NAME, SEMESTER FROM STUDENT
INNER JOIN STUDENT_RESULT ON STUDENT.ID= STUDENT_RESULT.ID
AND STUDENT_RESULT.CGPA = ( SELECT MAX( CGPA ) FROM STUDENT_RESULT )
