
/*CREATING TABLES*/
CREATE TABLE STUDENT(ID INT PRIMARY KEY, NAME varchar(50), SEMESTER INT, DATE_OF_B DATE)
CREATE TABLE STUDENT_RESULT(ID INT, CGPA FLOAT, FOREIGN KEY (ID) REFERENCES STUDENT(ID) )

/*INSERTING VALUES*/
INSERT INTO STUDENT VALUES(1, 'Rahim', 1, '10-OCT-90'), (2, 'Karim', 4, '11-JAN-90'), (3, 'Jamal', 5, '02-JUN-90'), (4, 'Karim', 11, '23-DEC-90')
INSERT INTO STUDENT_RESULT VALUES(1, 3.99), (2, 3.85), (3, 2.99), (4, 3.50)
INSERT INTO STUDENT VALUES(5, 'Joe', 12, '10-OCT-90')

/*VIEWING VALUES*/
SELECT * FROM STUDENT
SELECT * FROM STUDENT_RESULT

/*TABLE JOINS*/
SELECT * FROM STUDENT INNER JOIN STUDENT_RESULT ON STUDENT.ID= STUDENT_RESULT.ID
SELECT * FROM STUDENT LEFT JOIN STUDENT_RESULT ON STUDENT.ID= STUDENT_RESULT.ID
SELECT * FROM STUDENT RIGHT JOIN STUDENT_RESULT ON STUDENT.ID= STUDENT_RESULT.ID
SELECT * FROM STUDENT FULL JOIN STUDENT_RESULT ON STUDENT.ID= STUDENT_RESULT.ID
SELECT * FROM STUDENT FULL OUTER JOIN STUDENT_RESULT ON STUDENT.ID= STUDENT_RESULT.ID

/*DROPPING TABLES*/
DROP TABLE STUDENT, STUDENT_RESULT
